package com.example.projet.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.*;
import java.sql.Date;
import java.util.List;
@Entity
@Table(name = "commande")
@Data
@NoArgsConstructor
@AllArgsConstructor

public class Commande {

    @Id // Primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Automatically generated by the database
    @Column(name = "comd_id")
    private int comdId;

    @Column(name = "payement_method", nullable = false, length = 100)
    private String paymentMethod;

    @Column(name = "totale_amount", nullable = false)
    private double totalAmount;

    @Column(name = "delevrie_date")
    @Temporal(TemporalType.DATE)
    private Date deliveryDate;

    @Column(nullable = false, length = 100)
    private String status;

    @JsonIgnore
    @OneToMany(mappedBy = "commande", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    List<Ordere> orderes;

}
